URL = "https://consumer.fda.gov.tw/food/TFND.aspx?nodeID=178"

[TagType]
"全部" = ""
"穀物類" = "1"
"澱粉類" = "2"
"堅果及種子類" = "3"
"水果類" = "4"
"蔬菜類" = "5"
"藻類" = "6"
"菇類" = "7"
"豆類" = "8"
"肉類" = "9"
"魚貝類" = "10"
"蛋類" = "11"
"乳品類" = "12"
"油脂類" = "13"
"糖類" = "14"
"嗜好性飲料類" = "15"
"調味料及香辛料類" = "16"
"糕餅點心類" = "17"
"加工調理食品類" = "18"

[SearchField]
"樣品名稱" = "1"
"樣品內容物描述" = "2"
"樣品英文名稱" = "3"
"樣品中文俗名" = "4"
"樣品平均值名稱" = "5"
"樣品平均值內容物描述" = "6"
"樣品平均值英文名稱" = "7"
"樣品平均值中文俗名" = "8"